<?php

namespace AppBundle\Repository;

/**
 * RamasseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RamasseurRepository extends \Doctrine\ORM\EntityRepository
{
}
