<?php

namespace AppBundle\Repository;

/**
 * RamassageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RamassageRepository extends \Doctrine\ORM\EntityRepository
{
}
