CREATE TABLE producteur (id INT AUTO_INCREMENT NOT NULL, secteur_id INT NOT NULL
, ramasseur_id INT NOT NULL, code_producteur INT NOT NULL, prenom VARCHAR(255) D
EFAULT NULL, nom VARCHAR(255) DEFAULT NULL, adr2 VARCHAR(255) DEFAULT NULL, cp V
ARCHAR(255) DEFAULT NULL, ville VARCHAR(255) DEFAULT NULL, distance_fromagerie N
UMERIC(10, 0) DEFAULT NULL, INDEX IDX_7EDBEE109F7E4405 (secteur_id), INDEX IDX_7
EDBEE10839D537D (ramasseur_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLL
ATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE ramassage (id INT AUTO_INCREMENT NOT NULL, ramasseur_id INT NOT NUL
L, producteur_id INT NOT NULL, num_bon_ramassage INT NOT NULL, date_ramassage DA
TE DEFAULT NULL, nb_bidons INT DEFAULT NULL, nb_litres INT DEFAULT NULL, tx_mat_
grasses NUMERIC(10, 0) DEFAULT NULL, UNIQUE INDEX UNIQ_945DF2CF9D3E6258 (num_bon
_ramassage), INDEX IDX_945DF2CF839D537D (ramasseur_id), INDEX IDX_945DF2CFAB9BB3
00 (producteur_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_uni
code_ci ENGINE = InnoDB;
CREATE TABLE ramasseur (id INT AUTO_INCREMENT NOT NULL, secteur_id INT NOT NULL,
 code_ramasseur INT NOT NULL, prenom VARCHAR(255) DEFAULT NULL, nom VARCHAR(255)
 DEFAULT NULL, adr1 VARCHAR(255) DEFAULT NULL, adr2 VARCHAR(255) DEFAULT NULL, c
p VARCHAR(255) DEFAULT NULL, ville VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_
6873AF07C436D73F (code_ramasseur), INDEX IDX_6873AF079F7E4405 (secteur_id), PRIM
ARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE secteur (id INT AUTO_INCREMENT NOT NULL, code_secteur INT NOT NULL,
 libelle VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_8045251FB8E26183 (code_sec
teur), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGIN
E = InnoDB;
ALTER TABLE producteur ADD CONSTRAINT FK_7EDBEE109F7E4405 FOREIGN KEY (secteur_i
d) REFERENCES secteur (id);
ALTER TABLE producteur ADD CONSTRAINT FK_7EDBEE10839D537D FOREIGN KEY (ramasseur
_id) REFERENCES ramasseur (id);
ALTER TABLE ramassage ADD CONSTRAINT FK_945DF2CF839D537D FOREIGN KEY (ramasseur_
id) REFERENCES ramasseur (id);
ALTER TABLE ramassage ADD CONSTRAINT FK_945DF2CFAB9BB300 FOREIGN KEY (producteur
_id) REFERENCES producteur (id);
ALTER TABLE ramasseur ADD CONSTRAINT FK_6873AF079F7E4405 FOREIGN KEY (secteur_id
) REFERENCES secteur (id);
